<!doctype html>
<html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Finalizar pedido · {{ $negocio }}</title><meta name="theme-color" content="#070908"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700&display=swap" rel="stylesheet">@vite(['resources/css/app.css'])<style>body{overflow-y:auto}.checkout{max-width:720px;margin:auto;padding:26px 16px 60px}.checkout-hd{display:flex;align-items:center;gap:12px;margin-bottom:20px}.checkout-hd h1{font-size:25px}.choice{display:grid;grid-template-columns:1fr 1fr;gap:10px}.choice label{cursor:pointer}.choice input{position:absolute;opacity:0}.choice span{height:62px;border:1px solid var(--line-2);border-radius:13px;display:grid;place-items:center;color:var(--txt-2)}.choice input:checked+span{background:var(--green-dim);border-color:var(--green-line);color:var(--green);font-weight:600}.summary-item{display:flex;gap:12px;padding:10px 0;border-bottom:1px solid var(--line)}.summary-item:last-child{border:0}</style></head>
<body><main class="checkout">
<header class="checkout-hd"><a class="btn btn-sm" href="{{ route('pedido-online') }}">←</a><div><h1>Finalizar pedido</h1><div class="t-mute fs14">Completá tus datos para enviarlo</div></div></header>
@if($errors->any())<div class="notice notice-amber mb16"><span class="dot dot-amber"></span><div>{{ $errors->first() }}</div></div>@endif
<form method="POST" action="{{ route('pedido-online.guardar') }}" id="checkout-form">@csrf
@foreach($lineas as $i=>$linea)<input type="hidden" name="lineas[{{ $i }}][product_id]" value="{{ $linea['product_id'] }}"><input type="hidden" name="lineas[{{ $i }}][variant_id]" value="{{ $linea['product_variant_id'] }}"><input type="hidden" name="lineas[{{ $i }}][qty]" value="{{ $linea['qty'] }}"><input type="hidden" name="lineas[{{ $i }}][notes]" value="{{ $linea['notes'] }}">@endforeach
<section class="card"><div class="sec">¿Cómo lo recibís?</div><div class="choice"><label><input type="radio" name="type" value="delivery" checked><span>Delivery</span></label><label><input type="radio" name="type" value="retiro"><span>Retiro por el local</span></label></div></section>
<section class="card mt16"><div class="sec">Tus datos</div><div class="grid2"><div class="field"><label>Nombre</label><input class="inp" name="nombre" value="{{ old('nombre') }}" required maxlength="120" autocomplete="name"></div><div class="field"><label>WhatsApp</label><input class="inp" name="telefono" value="{{ old('telefono') }}" required maxlength="40" inputmode="tel" autocomplete="tel" placeholder="Con código de área"></div></div><div data-delivery><div class="field mt12"><label>Dirección</label><input class="inp" name="calle" maxlength="160" placeholder="Calle y número" autocomplete="street-address"></div><div class="grid2 mt12"><div class="field"><label>Detalle</label><input class="inp" name="detalle" maxlength="120" placeholder="Piso, timbre, referencia"></div><div class="field"><label>Zona</label><select class="inp" name="zone_id" data-zone><option value="" data-fee="0">Sin zona</option>@foreach($zonas as $zona)<option value="{{ $zona->id }}" data-fee="{{ $zona->delivery_fee }}">{{ $zona->name }} · @plata($zona->delivery_fee)</option>@endforeach</select></div></div></div><div class="field mt12"><label>Notas generales</label><textarea class="inp" name="notas" maxlength="300" placeholder="Indicaciones para el pedido o la entrega"></textarea></div></section>
<section class="card mt16"><div class="sec">Forma de pago</div><div class="field"><select class="inp" name="metodo_pago" data-payment><option value="">A definir</option><option value="cash">Efectivo</option><option value="qr">QR / transferencia</option><option value="debit">Tarjeta de débito</option><option value="credit">Tarjeta de crédito</option></select></div><div class="field mt12" data-cash hidden><label>¿Con cuánto pagás?</label><input class="inp" type="number" name="paga_con" min="0" step="1" inputmode="numeric"></div></section>
<section class="pane mt16"><div class="pane-hd"><h3>Tu pedido</h3></div>@foreach($lineas as $linea)<div class="summary-item"><strong>{{ $linea['qty'] }}×</strong><div class="grow">{{ $linea['product_name'] }} @if($linea['variant_name'])· {{ $linea['variant_name'] }}@endif @if($linea['notes'])<div class="fs13 t-amber">{{ $linea['notes'] }}</div>@endif</div><strong>@plata($linea['unit_price']*$linea['qty'])</strong></div>@endforeach<div class="lv mt12"><span class="k">Productos</span><span class="v">@plata($subtotal)</span></div><div class="lv" data-shipping-row><span class="k">Envío</span><span class="v" data-shipping>$0</span></div><div class="hr-strong"></div><div class="between"><span>Total</span><span class="money m-xl" data-total>@plata($subtotal)</span></div></section>
<button class="btn btn-primary btn-lg btn-block mt16">Confirmar pedido</button></form></main>
<script>const subtotal={{ $subtotal }};const pesos=c=>'$'+Math.round(c/100).toLocaleString('es-AR');function tipo(){return document.querySelector('[name=type]:checked').value}function actualizar(){const delivery=tipo()==='delivery';document.querySelector('[data-delivery]').hidden=!delivery;document.querySelector('[name=calle]').required=delivery;const fee=delivery?Number(document.querySelector('[data-zone]').selectedOptions[0].dataset.fee):0;document.querySelector('[data-shipping-row]').hidden=!delivery;document.querySelector('[data-shipping]').textContent=pesos(fee);document.querySelector('[data-total]').textContent=pesos(subtotal+fee);document.querySelector('[data-cash]').hidden=document.querySelector('[data-payment]').value!=='cash'}document.addEventListener('change',actualizar);actualizar();</script>
</body></html>
